//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatSanBongDaEntities : DbContext
    {
        public DatSanBongDaEntities()
            : base("name=DatSanBongDaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonDatSan> DonDatSans { get; set; }
        public virtual DbSet<LoaiSanBong> LoaiSanBongs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhanCongNhanVien> PhanCongNhanViens { get; set; }
        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SanBong> SanBongs { get; set; }
        public virtual DbSet<SuCo> SuCoes { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<TienIchSanBong> TienIchSanBongs { get; set; }
        public virtual DbSet<TrangThaiDonDat> TrangThaiDonDats { get; set; }
    }
}
