//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonDatSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatSan()
        {
            this.Reviews = new HashSet<Review>();
            this.SuCoes = new HashSet<SuCo>();
        }

        public int IDBooking { get; set; }
        [Required]
        public DateTime NgayBooking { get; set; }
        [Required]
        public TimeSpan start_time { get; set; }
        [Required]
        public TimeSpan end_time { get; set; }
        [Required]
        public decimal TongTien { get; set; }
        public bool TTThanhToan { get; set; } = false;
        public string admin_notes { get; set; }
        public string LyDoHuy { get; set; }
        public DateTime created_at { get; set; } = DateTime.Now;
        public DateTime updated_at { get; set; } = DateTime.Now;
        public int IDuser { get; set; }
        public int? IDPT { get; set; }
        public int? IDstatus { get; set; }
        public int IDSanBong { get; set; }

        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        public virtual SanBong SanBong { get; set; }
        public virtual TrangThaiDonDat TrangThaiDonDat { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuCo> SuCoes { get; set; }
    }
}
