//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongNhanVien
    {
        public int IDPhanCong { get; set; }
        public System.DateTime NgayPhanCong { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int IDuser { get; set; }
        public int IDSanBong { get; set; }
        public Nullable<int> IDAdmin { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual SanBong SanBong { get; set; }
    }
}
