//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int IDreview { get; set; }
        public byte rating { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public string comment { get; set; }
        public int IDSanBong { get; set; }
        public int IDuser { get; set; }
        public Nullable<int> IDBooking { get; set; }
    
        public virtual DonDatSan DonDatSan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanBong SanBong { get; set; }
    }
}
