//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanBong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanBong()
        {
            this.DonDatSans = new HashSet<DonDatSan>();
            this.PhanCongNhanViens = new HashSet<PhanCongNhanVien>();
            this.Reviews = new HashSet<Review>();
            this.SuCoes = new HashSet<SuCo>();
            this.TienIchSanBongs = new HashSet<TienIchSanBong>();
        }

        public int IDSanBong { get; set; }
        [Required]
        [StringLength(100)]
        public string TenSanBong { get; set; }
        [Required]
        [StringLength(255)]
        public string DiaChi { get; set; }
        [StringLength(100)]
        public string MoTaKichThuoc { get; set; }
        [Required]
        public decimal GiaThue { get; set; }
        public string MoTaSan { get; set; }
        [StringLength(255)]
        public string AnhSan { get; set; }
        public bool TrangThaiSan_ { get; set; } = true;
        public decimal AverageDanhGia { get; set; }
        public int TongLuotDanhGia { get; set; }
        public DateTime created_at { get; set; } = DateTime.Now;
        public DateTime updated_at { get; set; } = DateTime.Now;
        public int IDLoaiSan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatSan> DonDatSans { get; set; }
        public virtual LoaiSanBong LoaiSanBong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongNhanVien> PhanCongNhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuCo> SuCoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienIchSanBong> TienIchSanBongs { get; set; }
    }
}
