//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuCo
    {
        public int IDSuCo { get; set; }
        public string LoaiSuCo { get; set; }
        public string TrangThai { get; set; }
        public string resolution_notes { get; set; }
        public Nullable<System.DateTime> reported_at { get; set; }
        public Nullable<System.DateTime> resolved_at { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> IDuser { get; set; }
        public Nullable<int> IDBooking { get; set; }
        public Nullable<int> IDSanBong { get; set; }
        public Nullable<int> IDAdmin { get; set; }
        public string user_backup_info { get; set; }
        public string booking_backup_info { get; set; }
        public string sanBong_backup_info { get; set; }
        public string admin_backup_info { get; set; }
    
        public virtual DonDatSan DonDatSan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual SanBong SanBong { get; set; }
    }
}
