//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatSanBong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int IDnoti { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public Nullable<bool> is_read { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> sent_at { get; set; }
        public Nullable<int> IDuser { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
